{{- if .Values.arangodb.operator.enabled | not }}
apiVersion: v1
kind: Service
metadata:
  name: graph-db-server
spec:
  ports:
    - name: server
      port: 8529
      protocol: TCP
      targetPort: 8529
  selector:
    resoto: graphdb
    {{- include "resoto.selectorLabels" . | nindent 4 }}
{{- end }}
