{{- if .Values.resotometrics.serviceMonitor.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "resoto.fullname" . }}-resotometrics
  labels:
    resoto: metrics
    {{- include "resoto.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 9955
      protocol: TCP
      name: metrics
  selector:
    resoto: metrics
    {{- include "resoto.selectorLabels" . | nindent 4 }}
---
apiVersion: "monitoring.coreos.com/v1"
kind: ServiceMonitor
metadata:
  labels:
    resoto: metrics
    {{- include "resoto.labels" . | nindent 4 }}
  name: {{ include "resoto.fullname" . }}-resotometrics
spec:
  selector:
    matchLabels:
      resoto: metrics
      {{- include "resoto.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace | quote }}
  endpoints:
  - port: metrics
    interval: {{ .Values.resotometrics.serviceMonitor.interval }}
    scrapeTimeout: {{ .Values.resotometrics.serviceMonitor.scrapeTimeout }}
{{- end }}
