title: Some Engineering Helm Chart Repository
author:
  name: Some Engineering Inc.
  email: eng@some.engineering
markdown: kramdown
remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
  - jekyll-redirect-from
minima:
  skin: solarized-dark
  social_links:
    - { platform: github, user_url: 'https://github.com/someengineering' }
    - { platform: linkedin, user_url: 'https://linkedin.com/company/someengineering' }
    - { platform: youtube, user_url: 'https://youtube.com/@someengineering' }
