markdown: kramdown
theme: minima
minima:
  skin: solarized-dark
  social_links:
    - { platform: github, user_url: 'https://github.com/someengineering' }
    - { platform: linkedin, user_url: 'https://linkedin.com/company/someengineering' }
    - { platform: youtube, user_url: 'https://youtube.com/@someengineering' }
