apiVersion: v2
name: resoto
description: A Helm chart for Kubernetes

type: application

version: 0.3.3

appVersion: "2.3.0"
maintainers:
  - name: kushthedude
  - name: aquamatthias
    email: "eng@some.engineering"

icon: https://cdn.some.engineering/assets/resoto-logos/resoto-logo.svg
home: https://resoto.com
sources:
  - https://github.com/someengineering/resoto
keywords:
  - resoto
  - cloud
  - automation
  - aws
  - gcp
  - digitalocean
  - k8s
