apiVersion: v2
name: resoto
description: |
  A Helm chart for installing Resoto in Kubernetes.
  
  **Important**: This project is currently not being maintained. 
  If you are interested in taking over as a maintainer, please reach out to us at https://resoto.com/.
type: application
version: 0.10.4
appVersion: "3.8.0"
maintainers: []
icon: https://cdn.some.engineering/assets/resoto-logos/resoto-logo.svg
home: https://resoto.com
dependencies:
  - name: prometheus
    version: 18.1.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled
  - name: kube-arangodb
    alias: arangodb
    repository: https://arangodb.github.io/kube-arangodb
    condition: arangodb.operator.enabled
    version: 1.2.26
  - name: common
    alias: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 2.4.0
sources:
  - https://github.com/someengineering/resoto
keywords:
  - resoto
  - cloud
  - automation
  - aws
  - gcp
  - digitalocean
  - k8s
