apiVersion: v2
name: resoto
description: A Helm chart for Kubernetes
type: application
version: 0.3.13
appVersion: "2.4.4"
maintainers:
  - name: kushthedude
  - name: aquamatthias
    email: "eng@some.engineering"
icon: https://cdn.some.engineering/assets/resoto-logos/resoto-logo.svg
home: https://resoto.com
dependencies:
  - name: common
    alias: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 2.0.2
sources:
  - https://github.com/someengineering/resoto
keywords:
  - resoto
  - cloud
  - automation
  - aws
  - gcp
  - digitalocean
  - k8s
