apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ include "fixinventory.fullname" . }}-fixworker
  labels:
    fixinventory: worker
    {{- include "fixinventory.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      fixinventory: worker
      {{- include "fixinventory.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        fixinventory: worker
        {{- include "fixinventory.selectorLabels" . | nindent 8 }}
    spec:
      enableServiceLinks: false
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "fixinventory.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.fixworker.image.repository }}:{{ .Values.fixworker.image.tag | default .Values.image.tag | default .Chart.AppVersion }}"
          args:
          - --fixcore-uri
          - https://{{ include "fixinventory.fullname" . }}-fixcore:8900
          {{- if .Values.fixworker.overrides }}
          - --override
          {{- toYaml .Values.fixworker.overrides | nindent 10 }}
          {{- end }}
          {{- if .Values.fixworker.extraArgs }}
          {{- toYaml .Values.fixworker.extraArgs | nindent 10 }}
          {{- end }}
          env:
            - name: PSK
              valueFrom:
                secretKeyRef:
                  name: {{ include "fixinventory.fullname" . }}-psk
                  key: "psk"
          {{- if .Values.fixworker.extraEnv }}
          {{- toYaml .Values.fixworker.extraEnv | nindent 12 }}
          {{- end }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - name: https
              containerPort: 9956
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: https
              scheme: HTTPS
          resources:
            {{- toYaml .Values.fixworker.resources | nindent 12 }}
    {{- if .Values.fixworker.volumeMounts }}
          volumeMounts:
    {{- toYaml .Values.fixworker.volumeMounts | nindent 12 }}
    {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      affinity:
        # prefer to run not on the same node as the core
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                topologyKey: "kubernetes.io/hostname"
                labelSelector:
                  matchLabels:
                    fixinventory: core
        {{- with .Values.affinity }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- if .Values.fixworker.volumes }}
      volumes:
{{ toYaml .Values.fixworker.volumes | nindent 8 }}
{{- end }}
