{{- $name := printf "%s%s" (include "resoto.fullname" .) "-psk" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  labels:
    {{- include "resoto.labels" . | nindent 4 }}
data:
  # Check if the psk exists already (e.g. helm upgrade)
{{- $existingPskSecret := lookup "v1" "Secret" .Release.Namespace $name }}

{{- if not $existingPskSecret }}
  # Use a defined psk if available in values, otherwise generate a random one. Encode with base64 and quote it.
  psk: {{ ternary (randAlphaNum 32) .Values.psk (empty .Values.psk) | b64enc | quote }}
{{- else }}
  # psk does exist on cluster, build an object with the existing values
  psk: {{ index $existingPskSecret.data "psk" | quote }}
{{- end }}
