name: Package & Release Charts

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  package-release:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "C.K."
          git config user.email "98986935+some-ci@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: someengineering
        env:
          CR_TOKEN: ${{ secrets.SOME_CI_PAT }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.SOME_CI_PAT }}
          cname: helm.some.engineering
          publish_dir: ./
          exclude_assets: '.github,.gitignore,scripts'
          keep_files: true
          enable_jekyll: true
          user_name: C.K.
          user_email: 98986935+some-ci@users.noreply.github.com
