apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ include "resoto.fullname" . }}-resotocore
  labels:
    resoto: core
    {{- include "resoto.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      resoto: core
      {{- include "resoto.selectorLabels" . | nindent 6 }}
  # We can remove/change the strategy when the core no longer assumes it is a singleton.
  strategy:
    type: Recreate
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        resoto: core
        {{- include "resoto.selectorLabels" . | nindent 8 }}
    spec:
      enableServiceLinks: false
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "resoto.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.resotocore.image.repository }}:{{ .Values.resotocore.image.tag | default .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          args:
          - --graphdb-server
          - {{ .Values.resotocore.graphdb.server | quote }}
          - --graphdb-database
          - {{ .Values.resotocore.graphdb.database | quote }}
          - --graphdb-username
          - {{ .Values.resotocore.graphdb.username | quote }}
          - --override
          # add the host name of the resoto core service to the certificate
          - resotocore.api.host_certificate.san_dns_names={{ include "resoto.fullname" . }}-resotocore
          # if prometheus is enabled, define the tsdb url
          {{- if .Values.prometheus.enabled }}
          - resotocore.api.tsdb_proxy_url=http://resoto-prometheus-server/
          {{- end }}
          # bind to all available network interfaces
          - resotocore.api.web_hosts=0.0.0.0
          {{- if .Values.resotocore.overrides }}
          {{- toYaml .Values.resotocore.overrides | nindent 10 }}
          {{- end }}
          {{- if .Values.resotocore.extraArgs }}
          {{- toYaml .Values.resotocore.extraArgs | nindent 10 }}
          {{- end }}
          env:
          {{- if .Values.resotocore.graphdb.passwordSecret }}
          - name: RESOTOCORE_GRAPHDB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.resotocore.graphdb.passwordSecret.name }}
                key: {{ .Values.resotocore.graphdb.passwordSecret.key }}
          {{- end }}
          - name: PSK
            valueFrom:
              secretKeyRef:
                name: {{ include "resoto.fullname" . }}-psk
                key: "psk"
          {{- if .Values.resotocore.extraEnv }}
          {{- toYaml .Values.resotocore.extraEnv | nindent 10 }}
          {{- end }}
          - name: HELM_VERSION
            value: {{ .Chart.Version }}
          - name: HELM_APP_VERSION
            value: {{ .Chart.AppVersion }}
          ports:
            - name: api
              containerPort: 8900
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /system/ready
              port: api
              scheme: HTTPS
          resources:
            {{- toYaml .Values.resotocore.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            # prefer to schedule the core on the same node as the graphdb
            - weight: 1
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchExpressions:
                    - key: arango_deployment
                      operator: Exists
        {{- with .Values.affinity }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
