{{- if .Values.resotocore.ingress.enabled -}}
{{- $fullName := include "resoto.fullname" . -}}
{{- $fullName = (printf "%s%s%s" $fullName  "-resotocore" (ternary "" "-http" .Values.resotocore.ingress.useHttpsService)) }}
{{- $svcPort := .Values.resotocore.service.port -}}
{{- if and (contains "nginx" .Values.resotocore.ingress.className) (.Values.resotocore.ingress.useHttpsService) }}
  {{- if not (or (hasKey .Values.resotocore.ingress.annotations "nginx.ingress.kubernetes.io/backend-protocol") (hasKey .Values.resotocore.ingress.annotations "nginx.ingress.kubernetes.io/ssl-passthrough")) }}
  {{- $_ := set .Values.resotocore.ingress.annotations "nginx.ingress.kubernetes.io/backend-protocol" "HTTPS"}}
  {{- end }}
{{- end }}
apiVersion: {{ include "common.capabilities.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "resoto.labels" . | nindent 4 }}
  {{- with .Values.resotocore.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.resotocore.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.resotocore.ingress.className }}
  {{- end }}
  {{- if .Values.resotocore.ingress.tls }}
  tls:
    {{- range .Values.resotocore.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.resotocore.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if include "common.ingress.supportsPathType" $ }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
            {{- end }}
          {{- end }}
    {{- end }}
{{- end }}
