apiVersion: v1
kind: Service
metadata:
  name: {{ include "resoto.fullname" . }}-resotocore-http
  {{- with .Values.resotocore.service.http.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    resoto: core
    {{- include "resoto.labels" . | nindent 4 }}
spec:
  type: {{ .Values.resotocore.service.type }}
  ports:
    - port: {{ .Values.resotocore.service.port }}
      targetPort: http-port
      protocol: TCP
      name: http
  selector:
    resoto: core
    {{- include "resoto.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "resoto.fullname" . }}-resotocore
  {{- with .Values.resotocore.service.https.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    resoto: core
    {{- include "resoto.labels" . | nindent 4 }}
spec:
  type: {{ .Values.resotocore.service.type }}
  ports:
    - port: {{ .Values.resotocore.service.port }}
      targetPort: https-port
      protocol: TCP
      name: http
  selector:
    resoto: core
    {{- include "resoto.selectorLabels" . | nindent 4 }}
